
// scripts/generate-vfs.ts
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve, join } from 'path';

// Note: In a standard Node.js environment, __dirname would work.
// For Next.js/Studio environment, we might need to adjust path resolution.
// Let's assume process.cwd() gives us the project root.
const projectRoot = process.cwd();
const fontsDir = resolve(projectRoot, 'src/fonts/ttf');
const outputDir = resolve(projectRoot, 'src/fonts');
const outputFile = join(outputDir, 'vfs_fonts.ts');

try {
  // Ensure the source directory exists.
  if (!readdirSync(fontsDir)) {
      console.log(`Directory ${fontsDir} is empty. No fonts to process.`);
  }
} catch (e) {
    console.error(`Error reading fonts directory: ${fontsDir}. Make sure it exists and contains .ttf files.`);
    mkdirSync(fontsDir, { recursive: true });
    console.log(`Created directory: ${fontsDir}. Please add your .ttf font files there.`);
    process.exit(1); // Exit if the font source directory doesn't exist.
}

try {
  mkdirSync(outputDir, { recursive: true });
} catch {}

const files = readdirSync(fontsDir).filter(f => f.endsWith('.ttf'));

if (files.length === 0) {
    console.warn("No .ttf files found in src/fonts/ttf. The generated vfs_fonts.ts will be empty.");
}

const vfsEntries: string[] = files.map(file => {
  const filePath = join(fontsDir, file);
  const data = readFileSync(filePath);
  const base64 = data.toString('base64');
  return `  "${file}": "${base64}"`;
});

const fileContent = `// This file is auto-generated by scripts/generate-vfs.ts
const vfs = {
${vfsEntries.join(',\n')}
};

export default vfs;
`;

writeFileSync(outputFile, fileContent, "utf8");

console.log(`✅ vfs_fonts.ts generated successfully with ${files.length} font(s) at ${outputFile}.`);
